//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WineOnMyOwn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INZipCode
    {
        public Nullable<double> ZIP_Code { get; set; }
        public int ZipCodeId { get; set; }
    }
}
