//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;

namespace WineOnMyOwn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTBWinePermit : IEnumerable<TTBWinePermit>
    {
        public string PERMIT_NUMBER { get; set; }
        public string OWNER_NAME { get; set; }
        public string OPERATING_NAME { get; set; }
        public string STREET { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public Nullable<double> ZIP { get; set; }
        public Nullable<double> ZIP4 { get; set; }
        public string COUNTY { get; set; }
        public string FullAddress { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lng { get; set; }
        public int WinePermitId { get; set; }
        public Nullable<int> ZipCodeId { get; set; }
        public IEnumerator<TTBWinePermit> GetEnumerator()
        {
            throw new NotImplementedException();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }
    }
}
